### ISSUE TITLE
Cant run on win 10

### ISSUE THREAD

**Issue by therepo90** [williamjacksn/docker-excalibur#104]
Digest: sha256:f1953fb483e82ffa61648eebd674db0c2a63abcf6ae205084caa69f943258239
Status: Downloaded newer image for ghcr.io/williamjacksn/excalibur:latest
Creating new Excalibur configuration file in: /home/python/excalibur/excalibur.cfg
Traceback (most recent call last):
  File "/home/python/docker-excalibur/run.py", line 5, in <module>
    from excalibur import configuration as conf
  File "/home/python/venv/lib/python3.9/site-packages/excalibur/configuration.py", line 124, in <module>
    with open(EXCALIBUR_CONFIG, "w") as f:
PermissionError: [Errno 13] Permission denied: '/home/python/excalibur/excalibur.cfg'

**Comment by jpbaril** [comment]
Not limited to Windows. I have the same issue on a Linux host.

**Comment by williamjacksn** [comment]
I added instructions for running in Windows here:

https://github.com/williamjacksn/docker-excalibur/blob/master/docs/windows/README.md
