### ISSUE TITLE
No module named 'camelot.ext'

### ISSUE THREAD

**Issue by 0smboy** [williamjacksn/docker-excalibur#109]
<img width="1580" alt="image" src="https://github.com/williamjacksn/docker-excalibur/assets/91452062/17e38c6d-dbaa-47a8-a8e8-dc3b331fcd00">

**Comment by d0gleg** [comment]
I'm having exactly the same problem.

**Comment by 0smboy** [comment]
@d0gleg may be [this](https://github.com/camelot-dev/excalibur/issues/151#issuecomment-1368555901) will help

**Comment by williamjacksn** [comment]
I had to revert `camelot-py` back to 0.9.0. `excalibur` doesn't work with anything newer than that.

**Comment by williamjacksn** [comment]
Fixed in https://github.com/williamjacksn/docker-excalibur/commit/f8520034ea75bbf28c13325914524e89d1afa845
