### ISSUE TITLE
3.11 excalibur issues 

### ISSUE THREAD

**Issue by reeddolphin** [williamjacksn/docker-excalibur#68]
https://github.com/camelot-dev/excalibur/issues/151

I actually came looking for a container because I didn't want to deal with this issue/other local issues im having with ghostscript myself. but it sure does seem like excalibur doesn't like python versions above 3.7.

`docker container run -v ~/excalibur-data:/home/python/excalibur -e PORT=8081 -p 8081:8081 ghcr.io/williamjacksn/excalibur`

 `Traceback (most recent call last):
  File "/home/python/docker-excalibur/run.py", line 5, in <module>
    from excalibur import configuration as conf
  File "/home/python/venv/lib/python3.11/site-packages/excalibur/configuration.py", line 7, in <module>
    from backports.configparser import ConfigParser
  File "/home/python/venv/lib/python3.11/site-packages/backports/configparser/__init__.py", line 130, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)`

Totally separately, i assume this is user error completely, but any guess as to why this fails to open at http://127.0.0.1:8081/ ? 
`docker container run -v ~/excalibur-data:/home/python/excalibur -e PORT=8081 -p 8081:8081 ghcr.io/williamjacksn/excalibur:0.4.3`
<img width="827" alt="Screenshot 2023-02-18 at 9 28 18 AM" src="https://user-images.githubusercontent.com/29220016/219874162-3e90aa74-9aaa-44ac-9c52-07ec8721de40.png">

**Comment by williamjacksn** [comment]
I probably should not have tried to upgrade the version of Python in the image. I just reverted that change, so the `latest` image now runs on Python 3.9. Give that a try again.

The image tagged `0.4.3` was from before I wrote a custom entrypoint, and doesn't support listening on a custom port.

**Comment by williamjacksn** [comment]
Possible fixed in 09eceac53eb9092d08e180dcfb5ffd1be653b7fa

**Comment by kayarre** [comment]
Getting and error from local build

```sh
git clone git@github.com:williamjacksn/docker-excalibur.git

cd docker-excalibur

docker build . --tag excalibur 

docker container run -v ~/build/excalibur/data:/home/python/excalibur -e PORT=8081 -p 8081:8081 excalibur
```

```sh
Creating new Excalibur configuration file in: /home/python/excalibur/excalibur.cfg
Traceback (most recent call last):
  File "/home/python/docker-excalibur/run.py", line 8, in <module>
    from excalibur.www.app import create_app
  File "/home/python/venv/lib/python3.9/site-packages/excalibur/www/app.py", line 3, in <module>
    from flask import Flask, Blueprint
  File "/home/python/venv/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/home/python/venv/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/python/venv/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/python/venv/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/python/venv/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/python/venv/lib/python3.9/site-packages/markupsafe/__init__.py)
```

**Comment by williamjacksn** [comment]
@kayarre Update your clone, build the image, and try again. I rolled `markupsafe` back to 2.0.1, which is the last version to have `soft_unicode`.

**Comment by kayarre** [comment]
Huzzah! thank you!

**Comment by jbrodriguez** [comment]
hi, i'm getting the same `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`, this is a docker running on linux host

**Comment by williamjacksn** [comment]
Can you tell I don't actively use this project anymore? 🤣 

I think I need to roll all the way back to the `0.4.3` tag and add my custom entrypoint there. The Camelot and Excalibur projects have not seen updates in a long time, so it's dangerous to update their dependencies to the latest versions.

**Comment by jbrodriguez** [comment]
@williamjacksn that makes sense. i'm curious, are you using something other than excalibur+camelot or you just don't need this type of flow ?

if it's the former i'd like to know about it :)

i'm currently using tabula and although it works it hasn't received updates in quite a while, so i'm always looking for alternatives, in case it stops working

**Comment by williamjacksn** [comment]
I just don't have a need for this right now. It was always for personal stuff, and I found other ways to collect the data that I was originally extracting from PDFs.

And I take back what I said about Camelot, it actually had a new release last week!

https://pypi.org/project/camelot-py/0.11.0/

Anyway, I am happy to try to get this working as soon as I have some time.

**Comment by jbrodriguez** [comment]
thanks, i found this issue in the camelot repo

https://github.com/camelot-dev/camelot/issues/193#issuecomment-710004846

not sure what the base os is on your dockerfile (where the python:3.9.16.x draws from), but it looks like it requires something like `libgl1-mesa-glx` installed in order to work

i'll try to test it / create a pr, sometime this week

**Comment by jbrodriguez** [comment]
thanks  a lot man ! it's working now !
