### ISSUE TITLE
Having trouble getting this to run on a Windows 10 machine

### ISSUE THREAD

**Issue by Trellian** [williamjacksn/docker-excalibur#83]
Hi,

Thank you for this.  I'm a newb with Docker, so I apologize in advance... Any help you can give would be appreciated!

I'm running Windows 10 on an Intel Laptop.  
I've installed Docker Desktop
I have cloned this repo, and have successfully built it using

```
git clone git@github.com:williamjacksn/docker-excalibur.git

cd docker-excalibur

docker build . --tag excalibur 
```

when I try to run, I'm getting the following error
```
docker container run -v ~/build/excalibur/data:/home/python/excalibur -e PORT=8081 -p 8081:8081 excalibur
Creating new Excalibur configuration file in: /home/python/excalibur/excalibur.cfg
Traceback (most recent call last):
  File "/home/python/docker-excalibur/run.py", line 5, in <module>
    from excalibur import configuration as conf
  File "/home/python/venv/lib/python3.9/site-packages/excalibur/configuration.py", line 124, in <module>
    with open(EXCALIBUR_CONFIG, "w") as f:
PermissionError: [Errno 13] Permission denied: '/home/python/excalibur/excalibur.cfg'
```

I also tried doing all of that inside Docker Desktop, and while it sometimes doesn't give an error, and indicates that the container is running, I am unable to browse to the default port on 5000 (localhost:5000).  Inside Docker Desktop, I don't see any way to set the ports, except for the environment variable which I tried on 'PORT' with a value of 8080, 8081 and 8089.

Any input you might have would be much appreciated!

p.s. I have also occasionally got the same 'Permission denied : '/home/python/excalibur/excalibur.cfg' error inside Docker Desktop. I then delete the container and image, rebuild and run, and the error goes away. Then I can see the .cfg files in the files for the container, but still no access. I have granted firewall permissions for the private network

**Comment by therepo90** [comment]
getting same error

**Comment by williamjacksn** [comment]
I added instructions for running on Windows here:

https://github.com/williamjacksn/docker-excalibur/blob/master/docs/windows/README.md
